import "./globals.css";
import { Inter } from "next/font/google";
import { Head } from "./head";
import Sidebar from "@/components/Sidebar";
import { SessionProvider } from "@/components/SessionProvider";
import { getServerSession } from "next-auth/next";
import { authOptions } from "../pages/api/auth/[...nextauth]";
import Login from "@/components/Login";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <Head />
      <body className={inter.className}>
        <SessionProvider session={session}>
          {!session ? (
            <Login />
          ) : (
            <div className="flex">
              {/* TODO Sidebar */}
              <div className="overflow-y-auto max-w-xs h-screen md:min-w-[18rem] bg-slate-700">
                <Sidebar />
              </div>
              {/* Client Providers - notification component... */}
              <div className="bg-slate-800 text-slate-100 flex-1 ">
                {children}
              </div>
            </div>
          )}
        </SessionProvider>
      </body>
    </html>
  );
}
